import { sortByText } from "./sortText";
import { DEFAULT_TIME_SIGNATURE, Tune, makeId } from "./types";

export type Standard = {
  name: string;
  /** A commonly played (Real Book style) key, e.g. "Ab" or "Gm". */
  key: string;
  /** A typical practice tempo. */
  bpm: number;
  composer: string;
  timeSignature: string;
};

// [name, key, bpm, composer, timeSignature?] — keys and tempos are typical suggestions, not gospel.
type Row = [string, string, number, string, string?];

const ROWS: Row[] = [
  // --- Great American Songbook & swing standards ---
  ["All of Me", "C", 130, "Gerald Marks"],
  ["All of You", "Eb", 140, "Cole Porter"],
  ["All the Things You Are", "Ab", 120, "Jerome Kern"],
  ["Alone Together", "Dm", 130, "Arthur Schwartz"],
  ["Angel Eyes", "Cm", 66, "Matt Dennis"],
  ["April in Paris", "C", 130, "Vernon Duke"],
  ["As Time Goes By", "F", 80, "Herman Hupfeld"],
  ["At Last", "F", 62, "Harry Warren"],
  ["Autumn in New York", "Ab", 66, "Vernon Duke"],
  ["Autumn Leaves", "Gm", 120, "Joseph Kosma"],
  ["Baby, Won't You Please Come Home", "Bb", 110, "Charles Warfield"],
  ["Bewitched, Bothered and Bewildered", "Eb", 70, "Richard Rodgers"],
  ["Black Coffee", "Cm", 66, "Sonny Burke"],
  ["Blue Moon", "Eb", 110, "Richard Rodgers"],
  ["Body and Soul", "Db", 60, "Johnny Green"],
  ["But Beautiful", "F", 62, "Jimmy Van Heusen"],
  ["But Not for Me", "G", 120, "George Gershwin"],
  ["Bye Bye Blackbird", "C", 120, "Ray Henderson"],
  ["Can't Help Lovin' Dat Man", "F", 90, "Jerome Kern"],
  ["Cheek to Cheek", "C", 130, "Irving Berlin"],
  ["Come Rain or Come Shine", "Eb", 100, "Harold Arlen"],
  ["Crazy He Calls Me", "Eb", 60, "Carl Sigman"],
  ["Dancing on the Ceiling", "C", 130, "Richard Rodgers"],
  ["Darn That Dream", "Eb", 62, "Jimmy Van Heusen"],
  ["Day by Day", "C", 90, "Axel Stordahl"],
  ["Dearly Beloved", "F", 120, "Jerome Kern"],
  ["Dedicated to You", "C", 70, "Sammy Cahn"],
  ["Detour Ahead", "Eb", 66, "Herb Ellis"],
  ["Do Nothin' Till You Hear from Me", "Bb", 100, "Duke Ellington"],
  ["Don't Blame Me", "Eb", 80, "Jimmy McHugh"],
  ["Don't Get Around Much Anymore", "C", 130, "Duke Ellington"],
  ["Don't Explain", "Eb", 60, "Billie Holiday"],
  ["Easy Living", "F", 66, "Ralph Rainger"],
  ["Easy to Love", "C", 140, "Cole Porter"],
  ["Embraceable You", "Eb", 66, "George Gershwin"],
  ["Everything Happens to Me", "Bb", 66, "Matt Dennis"],
  ["Exactly Like You", "C", 130, "Jimmy McHugh"],
  ["Falling in Love with Love", "F", 130, "Richard Rodgers", "3/4"],
  ["Fascinating Rhythm", "Bb", 180, "George Gershwin"],
  ["Fine and Dandy", "C", 180, "Kay Swift"],
  ["Fly Me to the Moon", "C", 120, "Bart Howard"],
  ["Foggy Day, A", "F", 130, "George Gershwin"],
  ["For All We Know", "C", 66, "J. Fred Coots"],
  ["For Heaven's Sake", "Eb", 66, "Elise Bretton"],
  ["Forget Me", "C", 66, "Cole Porter"],
  ["Georgia on My Mind", "F", 66, "Hoagy Carmichael"],
  ["Get Out of Town", "C", 130, "Cole Porter"],
  ["Girl Talk", "F", 100, "Neal Hefti"],
  ["Give Me the Simple Life", "F", 130, "Rube Bloom"],
  ["Gone with the Wind", "F", 130, "Allie Wrubel"],
  ["Good Morning Heartache", "Cm", 60, "Irene Higginbotham"],
  ["Have You Met Miss Jones?", "F", 140, "Richard Rodgers"],
  ["Heart and Soul", "C", 110, "Hoagy Carmichael"],
  ["Here's That Rainy Day", "Eb", 62, "Jimmy Van Heusen"],
  ["Honeysuckle Rose", "F", 150, "Fats Waller"],
  ["How About You?", "F", 130, "Burton Lane"],
  ["How Deep Is the Ocean?", "C", 100, "Irving Berlin"],
  ["How High the Moon", "G", 200, "Morgan Lewis"],
  ["How Insensitive", "Dm", 120, "Antonio Carlos Jobim"],
  ["I Can't Get Started", "F", 66, "Vernon Duke"],
  ["I Can't Give You Anything but Love", "C", 130, "Jimmy McHugh"],
  ["I Concentrate on You", "Eb", 110, "Cole Porter"],
  ["I Could Write a Book", "Bb", 130, "Richard Rodgers"],
  ["I Cover the Waterfront", "Db", 62, "Johnny Green"],
  ["I Didn't Know What Time It Was", "Bb", 120, "Richard Rodgers"],
  ["I Fall in Love Too Easily", "C", 66, "Jule Styne"],
  ["I Got Rhythm", "Bb", 190, "George Gershwin"],
  ["I Hear a Rhapsody", "Eb", 120, "George Fragos"],
  ["I Let a Song Go Out of My Heart", "Eb", 100, "Duke Ellington"],
  ["I Love You", "Eb", 130, "Cole Porter"],
  ["I Love Paris", "Cm", 120, "Cole Porter"],
  ["I Mean You", "F", 150, "Thelonious Monk"],
  ["I Only Have Eyes for You", "Ab", 70, "Harry Warren"],
  ["I Remember You", "F", 130, "Victor Schertzinger"],
  ["I Should Care", "C", 66, "Axel Stordahl"],
  ["I Thought About You", "G", 110, "Jimmy Van Heusen"],
  ["I Wish I Knew", "Eb", 66, "Harry Warren"],
  ["I'll Be Seeing You", "F", 80, "Sammy Fain"],
  ["I'll Never Smile Again", "Eb", 66, "Ruth Lowe"],
  ["I'll Remember April", "C", 200, "Gene de Paul"],
  ["I'm Beginning to See the Light", "Eb", 130, "Duke Ellington"],
  ["I'm Old Fashioned", "C", 100, "Jerome Kern"],
  ["I've Got the World on a String", "F", 130, "Harold Arlen"],
  ["I've Got You Under My Skin", "Eb", 110, "Cole Porter"],
  ["If I Should Lose You", "Cm", 130, "Ralph Rainger"],
  ["If I Were a Bell", "F", 130, "Frank Loesser"],
  ["If You Could See Me Now", "Eb", 62, "Tadd Dameron"],
  ["In a Sentimental Mood", "F", 70, "Duke Ellington"],
  ["In the Still of the Night", "Eb", 100, "Cole Porter"],
  ["In the Wee Small Hours of the Morning", "Eb", 60, "David Mann"],
  ["Indian Summer", "Eb", 62, "Victor Herbert"],
  ["Isn't It Romantic?", "C", 120, "Richard Rodgers"],
  ["It Could Happen to You", "Eb", 140, "Jimmy Van Heusen"],
  ["It Don't Mean a Thing (If It Ain't Got That Swing)", "Gm", 150, "Duke Ellington"],
  ["It Had to Be You", "Eb", 120, "Isham Jones"],
  ["It Might as Well Be Spring", "F", 120, "Richard Rodgers"],
  ["It's All Right with Me", "Cm", 150, "Cole Porter"],
  ["It's Only a Paper Moon", "C", 130, "Harold Arlen"],
  ["It's You or No One", "C", 130, "Jule Styne"],
  ["Just Friends", "G", 66, "John Klenner"],
  ["Just in Time", "F", 140, "Jule Styne"],
  ["Just One of Those Things", "C", 160, "Cole Porter"],
  ["Lady Be Good", "C", 180, "George Gershwin"],
  ["Lazy River", "F", 110, "Hoagy Carmichael"],
  ["Let's Call the Whole Thing Off", "Eb", 130, "George Gershwin"],
  ["Let's Fall in Love", "C", 130, "Harold Arlen"],
  ["Like Someone in Love", "Eb", 62, "Jimmy Van Heusen"],
  ["Little Girl Blue", "Eb", 66, "Richard Rodgers"],
  ["Long Ago (and Far Away)", "Eb", 66, "Jerome Kern"],
  ["Love for Sale", "Cm", 150, "Cole Porter"],
  ["Love Is Here to Stay", "Eb", 100, "George Gershwin"],
  ["Love Me or Leave Me", "Eb", 130, "Walter Donaldson"],
  ["Lover", "C", 200, "Richard Rodgers", "3/4"],
  ["Lover Come Back to Me", "Eb", 200, "Sigmund Romberg"],
  ["Lover Man", "Dm", 60, "Jimmy Davis"],
  ["Lullaby of Birdland", "G", 140, "George Shearing"],
  ["Mack the Knife", "C", 130, "Kurt Weill"],
  ["Make Someone Happy", "F", 90, "Jule Styne"],
  ["Manhattan", "Eb", 130, "Richard Rodgers"],
  ["Meditation", "F", 130, "Antonio Carlos Jobim"],
  ["Misty", "Eb", 66, "Erroll Garner", "3/4"],
  ["Moonlight in Vermont", "Eb", 62, "Karl Suessdorf"],
  ["More Than You Know", "Eb", 62, "Vincent Youmans"],
  ["My Favorite Things", "Em", 170, "Richard Rodgers", "3/4"],
  ["My Foolish Heart", "Eb", 60, "Victor Young", "3/4"],
  ["My Funny Valentine", "Cm", 60, "Richard Rodgers"],
  ["My Heart Belongs to Daddy", "Eb", 120, "Cole Porter"],
  ["My Old Flame", "Eb", 62, "Arthur Johnston"],
  ["My One and Only Love", "F", 62, "Guy Wood"],
  ["My Romance", "C", 80, "Richard Rodgers"],
  ["My Shining Hour", "Eb", 180, "Harold Arlen"],
  ["My Ship", "Eb", 62, "Kurt Weill"],
  ["Nature Boy", "Dm", 90, "Eden Ahbez"],
  ["Nearness of You, The", "F", 62, "Hoagy Carmichael"],
  ["Nice Work If You Can Get It", "C", 130, "George Gershwin"],
  ["Night and Day", "C", 130, "Cole Porter"],
  ["Night We Called It a Day, The", "Eb", 62, "Matt Dennis"],
  ["Nobody Knows You When You're Down and Out", "C", 66, "Jimmy Cox"],
  ["Old Devil Moon", "Eb", 130, "Burton Lane"],
  ["Old Folks", "Eb", 62, "Willard Robison"],
  ["On a Slow Boat to China", "F", 130, "Frank Loesser"],
  ["On Green Dolphin Street", "C", 150, "Bronislau Kaper"],
  ["On the Sunny Side of the Street", "C", 130, "Jimmy McHugh"],
  ["Once in a While", "F", 90, "Michael Edwards"],
  ["One for My Baby (and One More for the Road)", "F", 60, "Harold Arlen"],
  ["Our Love Is Here to Stay", "Eb", 100, "George Gershwin"],
  ["Out of Nowhere", "G", 130, "Johnny Green"],
  ["Over the Rainbow", "Eb", 66, "Harold Arlen"],
  ["Pennies from Heaven", "C", 130, "Arthur Johnston"],
  ["Polka Dots and Moonbeams", "Eb", 62, "Jimmy Van Heusen"],
  ["Prelude to a Kiss", "Eb", 66, "Duke Ellington"],
  ["Rockin' in Rhythm", "C", 150, "Duke Ellington"],
  ["Ruby, My Dear", "Ab", 70, "Thelonious Monk"],
  ["Satin Doll", "C", 120, "Duke Ellington"],
  ["Sentimental Journey", "C", 90, "Les Brown"],
  ["September in the Rain", "C", 130, "Harry Warren"],
  ["September Song", "C", 70, "Kurt Weill"],
  ["Serenade in Blue", "Eb", 100, "Harry Warren"],
  ["Shadow of Your Smile, The", "F", 62, "Johnny Mandel", "3/4"],
  ["She's Funny That Way", "Eb", 90, "Neil Moret"],
  ["Skylark", "Eb", 62, "Hoagy Carmichael"],
  ["Smoke Gets in Your Eyes", "Eb", 66, "Jerome Kern"],
  ["So in Love", "Am", 120, "Cole Porter"],
  ["So What", "Dm", 138, "Miles Davis"],
  ["Softly, as in a Morning Sunrise", "Cm", 150, "Sigmund Romberg"],
  ["Solitude", "Eb", 62, "Duke Ellington"],
  ["Some Other Time", "Eb", 62, "Leonard Bernstein", "3/4"],
  ["Someone to Watch Over Me", "Eb", 62, "George Gershwin"],
  ["Something to Live For", "F", 66, "Billy Strayhorn"],
  ["Sometime Ago", "Eb", 66, "Sergio Mihanovich"],
  ["Sophisticated Lady", "Ab", 62, "Duke Ellington"],
  ["Speak Low", "Eb", 130, "Kurt Weill"],
  ["Spring Is Here", "Eb", 62, "Richard Rodgers"],
  ["Star Eyes", "Eb", 150, "Gene de Paul"],
  ["Stardust", "C", 62, "Hoagy Carmichael"],
  ["Stella by Starlight", "Bb", 130, "Victor Young"],
  ["Stompin' at the Savoy", "F", 170, "Edgar Sampson"],
  ["Stormy Weather", "F", 66, "Harold Arlen"],
  ["Sugar", "C", 100, "Stanley Turrentine"],
  ["Summertime", "Am", 90, "George Gershwin"],
  ["Sweet Lorraine", "C", 130, "Cliff Burwell"],
  ["Take the 'A' Train", "C", 170, "Billy Strayhorn"],
  ["Tea for Two", "Ab", 130, "Vincent Youmans"],
  ["Tenderly", "Eb", 70, "Walter Gross", "3/4"],
  ["That Old Feeling", "F", 66, "Lew Brown"],
  ["The Way You Look Tonight", "F", 120, "Jerome Kern"],
  ["There Is No Greater Love", "F", 130, "Isham Jones"],
  ["There Will Never Be Another You", "Eb", 140, "Harry Warren"],
  ["There's a Small Hotel", "F", 130, "Richard Rodgers"],
  ["They Can't Take That Away from Me", "Eb", 110, "George Gershwin"],
  ["Things Ain't What They Used to Be", "F", 120, "Mercer Ellington"],
  ["This Can't Be Love", "C", 150, "Richard Rodgers"],
  ["This Love of Mine", "Eb", 62, "Sol Parker"],
  ["Time After Time", "C", 100, "Jule Styne"],
  ["Time on My Hands", "Eb", 100, "Vincent Youmans"],
  ["Too Marvelous for Words", "C", 140, "Richard Whiting"],
  ["Touch of Your Lips, The", "Eb", 66, "Ray Noble"],
  ["Tune Up", "D", 200, "Miles Davis"],
  ["Twisted", "F", 140, "Wardell Gray"],
  ["Undecided", "C", 170, "Charlie Shavers"],
  ["Until the Real Thing Comes Along", "C", 120, "Sammy Cahn"],
  ["Very Early", "Eb", 130, "Bill Evans", "3/4"],
  ["Wave", "D", 130, "Antonio Carlos Jobim"],
  ["Way You Look Tonight, The", "F", 120, "Jerome Kern"],
  ["We'll Be Together Again", "Eb", 62, "Carl Fischer"],
  ["What Is This Thing Called Love?", "C", 180, "Cole Porter"],
  ["What's New?", "C", 62, "Bob Haggart"],
  ["When I Fall in Love", "Eb", 62, "Victor Young"],
  ["When Sunny Gets Blue", "F", 62, "Marvin Fisher"],
  ["When Lights Are Low", "Bb", 130, "Benny Carter"],
  ["Where or When", "Eb", 80, "Richard Rodgers"],
  ["While We're Young", "Eb", 80, "Alec Wilder"],
  ["Who Can I Turn To?", "Eb", 100, "Leslie Bricusse"],
  ["Why Was I Born?", "Eb", 62, "Jerome Kern"],
  ["Willow Weep for Me", "G", 80, "Ann Ronell"],
  ["Witchcraft", "F", 110, "Cy Coleman"],
  ["Yesterdays", "Dm", 130, "Jerome Kern"],
  ["You and the Night and the Music", "Cm", 140, "Arthur Schwartz"],
  ["You Are Too Beautiful", "Eb", 62, "Richard Rodgers"],
  ["You Brought a New Kind of Love to Me", "C", 130, "Sammy Fain"],
  ["You Don't Know What Love Is", "Fm", 66, "Gene de Paul"],
  ["You Go to My Head", "Db", 62, "J. Fred Coots"],
  ["You Stepped Out of a Dream", "Eb", 140, "Nacio Herb Brown"],
  ["You'd Be So Nice to Come Home To", "Cm", 150, "Cole Porter"],
  ["You're My Everything", "Eb", 130, "Harry Warren"],
  ["You're the Top", "C", 130, "Cole Porter"],
  ["Young at Heart", "C", 90, "Johnny Richards"],
  ["Zing! Went the Strings of My Heart", "Eb", 150, "James Hanley"],

  // --- Bebop & hard bop ---
  ["A Night in Tunisia", "Dm", 160, "Dizzy Gillespie"],
  ["Anthropology", "Bb", 220, "Charlie Parker"],
  ["Au Privave", "F", 180, "Charlie Parker"],
  ["Ah-Leu-Cha", "F", 200, "Charlie Parker"],
  ["Billie's Bounce", "F", 180, "Charlie Parker"],
  ["Bloomdido", "Bb", 180, "Charlie Parker"],
  ["Blue 'n' Boogie", "F", 240, "Dizzy Gillespie"],
  ["Blue Bossa", "Cm", 140, "Kenny Dorham", "4/4"],
  ["Blues for Alice", "F", 200, "Charlie Parker"],
  ["Blue Train", "Eb", 130, "John Coltrane"],
  ["Bluesette", "G", 130, "Toots Thielemans", "3/4"],
  ["Bouncin' with Bud", "F", 220, "Bud Powell"],
  ["Bright Size Life", "C", 170, "Pat Metheny"],
  ["Buzzy", "F", 200, "Charlie Parker"],
  ["Central Park West", "Ab", 62, "John Coltrane"],
  ["Confirmation", "F", 200, "Charlie Parker"],
  ["Constellation", "Bb", 220, "Charlie Parker"],
  ["Cheryl", "C", 200, "Charlie Parker"],
  ["Chi Chi", "F", 150, "Charlie Parker"],
  ["Cousin Mary", "Ab", 130, "John Coltrane"],
  ["Dexterity", "Bb", 220, "Charlie Parker"],
  ["Dizzy Atmosphere", "Ab", 260, "Dizzy Gillespie"],
  ["Donna Lee", "Ab", 220, "Charlie Parker"],
  ["Doxy", "Bb", 130, "Sonny Rollins"],
  ["Epistrophy", "Db", 150, "Thelonious Monk"],
  ["Evidence", "Eb", 150, "Thelonious Monk"],
  ["Falling Grace", "Bb", 130, "Steve Swallow"],
  ["Filthy McNasty", "F", 110, "Horace Silver"],
  ["Four", "Eb", 200, "Miles Davis"],
  ["Freddie Freeloader", "Bb", 120, "Miles Davis"],
  ["Giant Steps", "B", 280, "John Coltrane"],
  ["Groovin' High", "Eb", 200, "Dizzy Gillespie"],
  ["Half Nelson", "C", 220, "Miles Davis"],
  ["Hot House", "C", 220, "Tadd Dameron"],
  ["I Mean You", "F", 150, "Thelonious Monk"],
  ["In Walked Bud", "Db", 150, "Thelonious Monk"],
  ["Israel", "Fm", 150, "Johnny Carisi"],
  ["Jordu", "Cm", 170, "Duke Jordan"],
  ["Joy Spring", "F", 190, "Clifford Brown"],
  ["Ko-Ko", "Bb", 280, "Charlie Parker"],
  ["Lady Bird", "C", 200, "Tadd Dameron"],
  ["Lazy Bird", "G", 180, "John Coltrane"],
  ["Little Willie Leaps", "Bb", 200, "Miles Davis"],
  ["Milestones", "G", 210, "Miles Davis"],
  ["Mr. P.C.", "Cm", 200, "John Coltrane"],
  ["Moment's Notice", "Eb", 190, "John Coltrane"],
  ["Moose the Mooche", "Bb", 200, "Charlie Parker"],
  ["Nardis", "Em", 140, "Miles Davis"],
  ["Now's the Time", "F", 170, "Charlie Parker"],
  ["Oleo", "Bb", 220, "Sonny Rollins"],
  ["Ornithology", "G", 190, "Charlie Parker"],
  ["Pent-Up House", "C", 190, "Sonny Rollins"],
  ["Perdido", "Bb", 200, "Juan Tizol"],
  ["Recorda Me", "Dm", 150, "Joe Henderson"],
  ["Red Clay", "Fm", 130, "Freddie Hubbard"],
  ["Relaxin' at Camarillo", "C", 200, "Charlie Parker"],
  ["Ruby, My Dear", "Ab", 70, "Thelonious Monk"],
  ["Scrapple from the Apple", "F", 210, "Charlie Parker"],
  ["Segment", "F", 240, "Charlie Parker"],
  ["Serpent's Tooth", "Cm", 200, "Miles Davis"],
  ["Seven Come Eleven", "Bb", 220, "Charlie Christian"],
  ["Shaw 'Nuff", "F", 260, "Dizzy Gillespie"],
  ["Sippin' at Bells", "C", 200, "Miles Davis"],
  ["Solar", "Cm", 150, "Miles Davis"],
  ["Song for My Father", "Fm", 130, "Horace Silver"],
  ["Sonnymoon for Two", "Bb", 130, "Sonny Rollins"],
  ["St. Thomas", "C", 150, "Sonny Rollins"],
  ["Steeplechase", "Bb", 250, "Charlie Parker"],
  ["Stablemates", "Eb", 150, "Benny Golson"],
  ["Straight No Chaser", "F", 130, "Thelonious Monk"],
  ["Strode Rode", "C", 220, "Sonny Rollins"],
  ["Sweet Georgia Brown", "Ab", 160, "Ben Bernie"],
  ["The Chase", "Bb", 200, "Dexter Gordon"],
  ["The Theme", "Bb", 150, "Miles Davis"],
  ["Thriving from a Riff", "Bb", 250, "Charlie Parker"],
  ["Tune Up", "D", 200, "Miles Davis"],
  ["Well, You Needn't", "F", 150, "Thelonious Monk"],
  ["Whisper Not", "Cm", 120, "Benny Golson"],
  ["Woody 'n' You", "Db", 200, "Dizzy Gillespie"],
  ["Yardbird Suite", "C", 190, "Charlie Parker"],
  ["Yesterdays", "Dm", 130, "Jerome Kern"],

  // --- Modern jazz, post-bop & jazz compositions ---
  ["500 Miles High", "Em", 140, "Chick Corea"],
  ["Afro Blue", "Gm", 130, "Mongo Santamaria", "6/8"],
  ["Afro-Centric", "C", 150, "Joe Henderson"],
  ["Airegin", "Fm", 200, "Sonny Rollins"],
  ["All Blues", "G", 150, "Miles Davis", "6/8"],
  ["Along Came Betty", "Bb", 130, "Benny Golson"],
  ["Alice in Wonderland", "F", 130, "Sammy Fain", "3/4"],
  ["Beatrice", "Bb", 130, "Sam Rivers"],
  ["Bessie's Blues", "Bb", 130, "John Coltrane"],
  ["Black Narcissus", "Dm", 120, "Joe Henderson"],
  ["Black Orpheus", "Am", 140, "Luiz Bonfá"],
  ["Blues March", "Bb", 130, "Benny Golson"],
  ["Body and Soul", "Db", 60, "Johnny Green"],
  ["Bolivia", "Eb", 180, "Cedar Walton"],
  ["Cantaloupe Island", "Fm", 130, "Herbie Hancock"],
  ["Caravan", "Cm", 150, "Juan Tizol"],
  ["Chameleon", "Bbm", 108, "Herbie Hancock"],
  ["Countdown", "Eb", 300, "John Coltrane"],
  ["Crescent", "Dm", 66, "John Coltrane"],
  ["Dolphin Dance", "Eb", 100, "Herbie Hancock"],
  ["E.S.P.", "C", 170, "Wayne Shorter"],
  ["Equinox", "Cm", 130, "John Coltrane"],
  ["Fee-Fi-Fo-Fum", "Bb", 190, "Wayne Shorter"],
  ["Footprints", "Cm", 150, "Wayne Shorter", "6/8"],
  ["Fall", "Bb", 150, "Wayne Shorter"],
  ["Gingerbread Boy", "C", 170, "Jimmy Heath"],
  ["Have You Met Miss Jones?", "F", 140, "Richard Rodgers"],
  ["Impressions", "Dm", 240, "John Coltrane"],
  ["Inner Urge", "Ebm", 200, "Joe Henderson"],
  ["Invitation", "Cm", 150, "Bronislau Kaper"],
  ["Iris", "Eb", 100, "Wayne Shorter"],
  ["Isotope", "Bb", 150, "Joe Henderson"],
  ["Jinrikisha", "Eb", 150, "Wayne Shorter"],
  ["Juju", "Bb", 130, "Wayne Shorter"],
  ["Lush Life", "Db", 60, "Billy Strayhorn"],
  ["Maiden Voyage", "Dm", 130, "Herbie Hancock"],
  ["Naima", "Ab", 62, "John Coltrane"],
  ["Nefertiti", "Fm", 100, "Wayne Shorter"],
  ["Nica's Dream", "Fm", 150, "Horace Silver"],
  ["Oleo", "Bb", 220, "Sonny Rollins"],
  ["One Finger Snap", "F", 200, "Herbie Hancock"],
  ["Orbits", "C", 190, "Wayne Shorter"],
  ["Peace", "Db", 62, "Horace Silver"],
  ["Pinocchio", "Cm", 200, "Wayne Shorter"],
  ["Prince of Darkness", "Cm", 200, "Wayne Shorter"],
  ["Ram-Bunk-Shush", "Dm", 200, "Bobby Timmons"],
  ["Reflections", "Bb", 130, "Thelonious Monk"],
  ["Resolution", "Cm", 140, "John Coltrane"],
  ["Rhythm-a-Ning", "Bb", 220, "Thelonious Monk"],
  ["'Round Midnight", "Ebm", 60, "Thelonious Monk"],
  ["Sidewinder, The", "Bb", 130, "Lee Morgan"],
  ["Sister Sadie", "Bb", 130, "Horace Silver"],
  ["Skating in Central Park", "F", 100, "John Lewis"],
  ["Speak No Evil", "Cm", 130, "Wayne Shorter"],
  ["Spain", "Bm", 130, "Chick Corea"],
  ["Stolen Moments", "Cm", 120, "Oliver Nelson"],
  ["The Peacocks", "C", 62, "Jimmy Rowles"],
  ["The Summer Knows", "Am", 62, "Michel Legrand"],
  ["Tom Thumb", "Db", 130, "Wayne Shorter"],
  ["Turn Out the Stars", "Ab", 62, "Bill Evans", "3/4"],
  ["Up Jumped Spring", "F", 150, "Freddie Hubbard", "3/4"],
  ["Virgo", "Bb", 150, "Wayne Shorter"],
  ["Waltz for Debby", "F", 170, "Bill Evans", "3/4"],
  ["Windows", "C", 190, "Chick Corea"],
  ["Witch Hunt", "Fm", 190, "Wayne Shorter"],
  ["Yes or No", "Bb", 130, "Wayne Shorter"],
  ["You Must Believe in Spring", "Eb", 62, "Michel Legrand"],

  // --- Latin, bossa nova & samba ---
  ["A Felicidade", "Dm", 130, "Antonio Carlos Jobim"],
  ["Agua de Beber", "Dm", 140, "Antonio Carlos Jobim"],
  ["Barquinho", "Ab", 130, "Roberto Menescal"],
  ["Beautiful Love", "Dm", 170, "Victor Young"],
  ["Black Orpheus", "Am", 140, "Luiz Bonfá"],
  ["Chega de Saudade", "Dm", 140, "Antonio Carlos Jobim"],
  ["Corcovado", "Am", 130, "Antonio Carlos Jobim"],
  ["Desafinado", "F", 140, "Antonio Carlos Jobim"],
  ["Dindi", "C", 130, "Antonio Carlos Jobim"],
  ["Girl from Ipanema, The", "F", 130, "Antonio Carlos Jobim"],
  ["Insensatez", "Dm", 120, "Antonio Carlos Jobim"],
  ["No Problem", "Eb", 150, "Duke Jordan"],
  ["Once I Loved", "Bb", 140, "Antonio Carlos Jobim"],
  ["One Note Samba", "F", 150, "Antonio Carlos Jobim"],
  ["Quiet Nights of Quiet Stars", "D", 130, "Antonio Carlos Jobim"],
  ["Recorda Me", "Dm", 150, "Joe Henderson"],
  ["Samba de Orfeu", "Dm", 150, "Luiz Bonfá"],
  ["So Danço Samba", "Dm", 150, "Antonio Carlos Jobim"],
  ["Song for My Father", "Fm", 130, "Horace Silver"],
  ["Triste", "Eb", 130, "Antonio Carlos Jobim"],
  ["Wave", "D", 130, "Antonio Carlos Jobim"],
  ["Estate", "Dm", 120, "Bruno Martino"],
  ["Doralice", "Cm", 140, "Dorival Caymmi"],
  ["Vivo Sonhando", "Db", 130, "Antonio Carlos Jobim"],
  ["Recado Bossa Nova", "Fm", 130, "Djalma Ferreira"],
  ["Brazil", "C", 130, "Ary Barroso"],
  ["Poinciana", "Gm", 90, "Nat Simon"],
  ["Tico Tico", "C", 200, "Zequinha de Abreu"],
  ["Besame Mucho", "Dm", 100, "Consuelo Velázquez"],
  ["Perfidia", "Am", 100, "Alberto Domínguez"],
  ["Mas Que Nada", "Gm", 130, "Jorge Ben"],
  ["Tin Tin Deo", "Dm", 150, "Chano Pozo"],
  ["Manteca", "Bb", 130, "Dizzy Gillespie"],
  ["Oye Como Va", "Am", 130, "Tito Puente"],
  ["Cubano Chant", "Bb", 130, "Ray Bryant"],
  ["Mambo Inn", "C", 130, "Mario Bauza"],
  ["El Cumbanchero", "Dm", 150, "Rafael Hernández"],

  // --- Blues, funk & soul-jazz ---
  ["Blues in the Closet", "Bb", 150, "Oscar Pettiford"],
  ["Billie's Bounce", "F", 180, "Charlie Parker"],
  ["C Jam Blues", "C", 140, "Duke Ellington"],
  ["Doxy", "Bb", 130, "Sonny Rollins"],
  ["Equinox", "Cm", 130, "John Coltrane"],
  ["Georgia on My Mind", "F", 66, "Hoagy Carmichael"],
  ["Gee Baby, Ain't I Good to You", "Eb", 80, "Andy Razaf"],
  ["Hit the Road Jack", "Am", 130, "Percy Mayfield"],
  ["Jelly Roll", "Bb", 130, "Charles Mingus"],
  ["Mercy, Mercy, Mercy", "F", 100, "Joe Zawinul"],
  ["Now's the Time", "F", 170, "Charlie Parker"],
  ["Sack o' Woe", "Bb", 130, "Cannonball Adderley"],
  ["Sermonette", "Bb", 130, "Cannonball Adderley"],
  ["Watermelon Man", "F", 130, "Herbie Hancock"],
  ["Tenor Madness", "Bb", 140, "Sonny Rollins"],
  ["The Sidewinder", "Bb", 130, "Lee Morgan"],
  ["Blue Monk", "Bb", 110, "Thelonious Monk"],
  ["Blue Seven", "Bb", 130, "Sonny Rollins"],
  ["Bags' Groove", "F", 120, "Milt Jackson"],
  ["Cheesecake", "Bb", 130, "Dexter Gordon"],
  ["Mr. Magic", "Ab", 100, "Grover Washington Jr."],
  ["Take Five", "Ebm", 174, "Paul Desmond", "5/4"],
  ["Blue Rondo à la Turk", "Cm", 200, "Dave Brubeck", "9/8"],
  ["Unsquare Dance", "Am", 150, "Dave Brubeck", "7/4"],
  ["Comin' Home Baby", "Bb", 110, "Bob Dorough"],
  ["Killer Joe", "Gm", 130, "Benny Golson"],
  ["Moanin'", "Cm", 130, "Bobby Timmons"],
  ["Dat Dere", "F", 100, "Bobby Timmons"],
  ["This Here", "F", 100, "Bobby Timmons", "3/4"],
  ["Work Song", "Fm", 110, "Nat Adderley"],
  ["Jive Samba", "F", 150, "Nat Adderley"],
  ["Hard Times", "Bb", 130, "Ray Charles"],
  ["Every Day I Have the Blues", "Bb", 110, "Memphis Slim"],
  ["Stormy Monday", "G", 66, "T-Bone Walker"],
  ["Sonnymoon for Two", "Bb", 130, "Sonny Rollins"],

  // --- Waltzes & other meters ---
  ["Alice in Wonderland", "F", 130, "Sammy Fain", "3/4"],
  ["Bluesette", "G", 130, "Toots Thielemans", "3/4"],
  ["Blue in Green", "Dm", 62, "Miles Davis"],
  ["Emily", "F", 62, "Johnny Mandel", "3/4"],
  ["Falling in Love with Love", "F", 130, "Richard Rodgers", "3/4"],
  ["Gloria's Step", "Db", 130, "Scott LaFaro", "3/4"],
  ["Jitterbug Waltz", "Eb", 170, "Fats Waller", "3/4"],
  ["My Favorite Things", "Em", 170, "Richard Rodgers", "3/4"],
  ["On Green Dolphin Street", "C", 150, "Bronislau Kaper"],
  ["Peri's Scope", "Db", 130, "Bill Evans", "3/4"],
  ["Solar", "Cm", 150, "Miles Davis"],
  ["Someday My Prince Will Come", "Bb", 130, "Frank Churchill", "3/4"],
  ["Sweet Pea", "F", 130, "Billy Strayhorn", "3/4"],
  ["Tenderly", "Eb", 70, "Walter Gross", "3/4"],
  ["The Girl Next Door", "Eb", 130, "Hugh Martin"],
  ["The Shadow of Your Smile", "F", 62, "Johnny Mandel", "3/4"],
  ["Three Views of a Secret", "Bb", 100, "Jaco Pastorius"],
  ["Waltz for Debby", "F", 170, "Bill Evans", "3/4"],
  ["Wives and Lovers", "Eb", 150, "Burt Bacharach", "3/4"],
  ["Where Is Love?", "Eb", 100, "Lionel Bart", "3/4"],
  ["You Don't Know What Love Is", "Fm", 66, "Gene de Paul"],
  ["Nardis", "Em", 140, "Miles Davis"],
  ["Peace Piece", "C", 62, "Bill Evans"],
  ["Time Remembered", "F", 62, "Bill Evans", "3/4"],
  ["Interplay", "C", 130, "Bill Evans"],
  ["Re: Person I Knew", "Db", 130, "Bill Evans"],
  ["Funkallero", "Bb", 130, "Bill Evans"],
  ["Very Early", "Eb", 130, "Bill Evans", "3/4"],
  ["Peri's Scope", "Db", 130, "Bill Evans"],

  // --- Duke Ellington / Strayhorn / big band favorites ---
  ["Caravan", "Cm", 150, "Juan Tizol"],
  ["Chelsea Bridge", "Ab", 62, "Billy Strayhorn"],
  ["Daydream", "C", 62, "Billy Strayhorn"],
  ["Drop Me Off in Harlem", "F", 130, "Duke Ellington"],
  ["Isfahan", "Eb", 62, "Billy Strayhorn"],
  ["Johnny Come Lately", "Bb", 150, "Billy Strayhorn"],
  ["Lotus Blossom", "F", 62, "Billy Strayhorn"],
  ["Mood Indigo", "Ab", 66, "Duke Ellington"],
  ["Perdido", "Bb", 200, "Juan Tizol"],
  ["Raincheck", "F", 130, "Billy Strayhorn"],
  ["Rocks in My Bed", "F", 130, "Duke Ellington"],
  ["Star-Crossed Lovers", "Ab", 62, "Duke Ellington"],
  ["Take the A Train", "C", 170, "Billy Strayhorn"],
  ["The Single Petal of a Rose", "Eb", 62, "Duke Ellington"],
  ["Upper Manhattan Medical Group", "F", 130, "Billy Strayhorn"],
  ["Warm Valley", "Eb", 62, "Duke Ellington"],
  ["Jeep's Blues", "F", 100, "Duke Ellington"],
  ["Cotton Tail", "Bb", 200, "Duke Ellington"],
  ["Sophisticated Lady", "Ab", 62, "Duke Ellington"],
  ["Prelude to a Kiss", "Eb", 66, "Duke Ellington"],
  ["Just Squeeze Me", "Eb", 100, "Duke Ellington"],
  ["Mood Indigo", "Ab", 66, "Duke Ellington"],
  ["Satin Doll", "C", 120, "Duke Ellington"],
  ["In a Mellow Tone", "Ab", 130, "Duke Ellington"],
  ["Come Sunday", "Ab", 62, "Duke Ellington"],
  ["Azure", "Eb", 62, "Duke Ellington"],

  // --- Charles Mingus, Monk, & other jazz-composer favorites ---
  ["Bemsha Swing", "C", 150, "Thelonious Monk"],
  ["Bye-Ya", "C", 200, "Thelonious Monk"],
  ["Criss Cross", "Bb", 130, "Thelonious Monk"],
  ["Crepuscule with Nellie", "Eb", 62, "Thelonious Monk"],
  ["Hackensack", "F", 200, "Thelonious Monk"],
  ["Little Rootie Tootie", "F", 200, "Thelonious Monk"],
  ["Misterioso", "Bb", 110, "Thelonious Monk"],
  ["Monk's Dream", "C", 130, "Thelonious Monk"],
  ["Monk's Mood", "C", 62, "Thelonious Monk"],
  ["Pannonica", "Eb", 62, "Thelonious Monk"],
  ["'Round Midnight", "Ebm", 60, "Thelonious Monk"],
  ["Trinkle Tinkle", "Db", 150, "Thelonious Monk"],
  ["Ugly Beauty", "F", 130, "Thelonious Monk", "3/4"],
  ["Goodbye Pork Pie Hat", "F", 62, "Charles Mingus"],
  ["Fables of Faubus", "Bb", 130, "Charles Mingus"],
  ["Nostalgia in Times Square", "Cm", 150, "Charles Mingus"],
  ["Pithecanthropus Erectus", "Cm", 110, "Charles Mingus"],
  ["Better Get Hit in Yo' Soul", "Gm", 150, "Charles Mingus"],
  ["Jump Monk", "Bb", 130, "Charles Mingus"],
  ["Nica's Dream", "Fm", 150, "Horace Silver"],
  ["The Preacher", "Bb", 130, "Horace Silver"],
  ["Doodlin'", "F", 100, "Horace Silver"],
  ["Strollin'", "F", 130, "Horace Silver"],
  ["Lonely Woman", "Fm", 62, "Ornette Coleman"],
  ["Blues Connotation", "Bb", 130, "Ornette Coleman"],
  ["Ramblin'", "Bb", 130, "Ornette Coleman"],
  ["Turnaround", "Bb", 130, "Ornette Coleman"],
  ["When Will the Blues Leave", "Bb", 130, "Ornette Coleman"],
  ["Una Muy Bonita", "Cm", 130, "Ornette Coleman"],
  ["Mood Indigo", "Ab", 66, "Duke Ellington"],
  ["Pinocchio", "Cm", 200, "Wayne Shorter"],
  ["Children of the Night", "Bb", 190, "Wayne Shorter"],
  ["Lady Day", "Eb", 66, "John Coltrane"],
  ["Like Sonny", "F", 130, "John Coltrane"],
  ["Syeeda's Song Flute", "C", 200, "John Coltrane"],
  ["Spiral", "F", 190, "John Coltrane"],
  ["26-2", "Eb", 220, "John Coltrane"],
  ["Satellite", "Eb", 200, "John Coltrane"],
  ["Central Park West", "Ab", 62, "John Coltrane"],
  ["Village Blues", "F", 110, "John Coltrane"],
  ["Wise One", "Bb", 62, "John Coltrane"],
  ["Alabama", "Bb", 62, "John Coltrane"],

  // --- Pop, Broadway, film & other jazz-friendly tunes ---
  ["A Time for Love", "F", 62, "Johnny Mandel"],
  ["Agua de Marco", "Gm", 130, "Antonio Carlos Jobim"],
  ["Alfie", "F", 62, "Burt Bacharach"],
  ["All Through the Night", "F", 100, "Jerome Kern"],
  ["Almost Like Being in Love", "F", 130, "Frederick Loewe"],
  ["Anything Goes", "F", 150, "Cole Porter"],
  ["As Long as He Needs Me", "Eb", 66, "Lionel Bart", "3/4"],
  ["Bali Ha'i", "Bb", 66, "Richard Rodgers"],
  ["Beyond the Sea", "Bb", 130, "Charles Trenet"],
  ["Big Spender", "C", 130, "Cy Coleman"],
  ["Blue Skies", "C", 130, "Irving Berlin"],
  ["Blue Velvet", "F", 66, "Bernie Wayne", "3/4"],
  ["Bye Bye Baby", "C", 130, "Jule Styne"],
  ["Cabaret", "C", 130, "John Kander"],
  ["Call Me Irresponsible", "Bb", 130, "Jimmy Van Heusen"],
  ["Ca'purange", "F", 110, "Lee Morgan"],
  ["Charade", "F", 66, "Henry Mancini", "3/4"],
  ["Cheek to Cheek", "C", 130, "Irving Berlin"],
  ["Come Fly with Me", "Eb", 130, "Jimmy Van Heusen"],
  ["Come Sunday", "Ab", 62, "Duke Ellington"],
  ["Comes Love", "Db", 130, "Sam H. Stept"],
  ["Cry Me a River", "Cm", 66, "Arthur Hamilton"],
  ["Dancing in the Dark", "F", 90, "Arthur Schwartz"],
  ["Days of Wine and Roses", "F", 110, "Henry Mancini"],
  ["Do You Know What It Means to Miss New Orleans", "F", 62, "Louis Alter"],
  ["Don't Get Around Much Anymore", "C", 130, "Duke Ellington"],
  ["Emily", "F", 62, "Johnny Mandel", "3/4"],
  ["Everything I've Got", "F", 130, "Richard Rodgers"],
  ["Feelin' Good", "Gm", 100, "Leslie Bricusse"],
  ["Girl from Ipanema", "F", 130, "Antonio Carlos Jobim"],
  ["Good Life, The", "F", 100, "Sacha Distel"],
  ["Hello, Dolly!", "Eb", 130, "Jerry Herman"],
  ["Here's to Life", "Ab", 62, "Artie Butler"],
  ["Hey There", "F", 66, "Richard Adler"],
  ["I Could Have Danced All Night", "F", 100, "Frederick Loewe"],
  ["I Get a Kick Out of You", "F", 130, "Cole Porter"],
  ["I Got It Bad (and That Ain't Good)", "Eb", 62, "Duke Ellington"],
  ["I Left My Heart in San Francisco", "C", 66, "George Cory"],
  ["I Love a Piano", "C", 170, "Irving Berlin"],
  ["I Wish You Love", "Gm", 66, "Charles Trenet"],
  ["I'm Getting Sentimental Over You", "Bb", 130, "George Bassman"],
  ["Ill Wind", "F", 62, "Harold Arlen"],
  ["It Never Entered My Mind", "Eb", 62, "Richard Rodgers"],
  ["It's Magic", "F", 100, "Jule Styne"],
  ["It's Easy to Remember", "Eb", 62, "Richard Rodgers"],
  ["Jeepers Creepers", "C", 150, "Harry Warren"],
  ["Just the Way You Are", "Ab", 100, "Billy Joel"],
  ["La Vie en Rose", "C", 80, "Louiguy"],
  ["Lady Is a Tramp, The", "Eb", 150, "Richard Rodgers"],
  ["Let's Get Lost", "Eb", 120, "Jimmy McHugh"],
  ["Let It Snow", "C", 130, "Jule Styne"],
  ["Love Walked In", "F", 90, "George Gershwin"],
  ["Mona Lisa", "C", 66, "Jay Livingston"],
  ["Moon River", "C", 66, "Henry Mancini", "3/4"],
  ["Moonglow", "C", 100, "Will Hudson"],
  ["Mood Indigo", "Ab", 66, "Duke Ellington"],
  ["More", "C", 100, "Riz Ortolani"],
  ["My Way", "C", 66, "Paul Anka"],
  ["Nobody Does It Better", "F", 66, "Marvin Hamlisch"],
  ["Ol' Man River", "C", 66, "Jerome Kern"],
  ["On Broadway", "Am", 110, "Barry Mann"],
  ["On the Street Where You Live", "Eb", 130, "Frederick Loewe"],
  ["One Note Samba", "F", 150, "Antonio Carlos Jobim"],
  ["People", "C", 66, "Jule Styne", "3/4"],
  ["'Round Midnight", "Ebm", 60, "Thelonious Monk"],
  ["Secret Love", "Bb", 66, "Sammy Fain", "3/4"],
  ["Shiny Stockings", "F", 110, "Frank Foster"],
  ["Sing, Sing, Sing", "Bb", 150, "Louis Prima"],
  ["Slow Hot Wind", "Eb", 100, "Henry Mancini"],
  ["Small Day Tomorrow", "Eb", 66, "Bob Dorough"],
  ["Speak Softly Love", "Fm", 66, "Nino Rota", "3/4"],
  ["Sunny", "Bm", 110, "Bobby Hebb"],
  ["Sweet Home Chicago", "E", 110, "Robert Johnson"],
  ["Tangerine", "Gm", 130, "Victor Schertzinger"],
  ["The Christmas Song", "Eb", 66, "Mel Tormé"],
  ["The Lady Is a Tramp", "Eb", 150, "Richard Rodgers"],
  ["The Lamp Is Low", "F", 62, "Peter DeRose"],
  ["The Look of Love", "Dm", 100, "Burt Bacharach"],
  ["The Nearness of You", "F", 62, "Hoagy Carmichael"],
  ["The Second Time Around", "F", 66, "Jimmy Van Heusen"],
  ["The Very Thought of You", "G", 62, "Ray Noble"],
  ["The Way We Were", "F", 66, "Marvin Hamlisch"],
  ["This Masquerade", "Am", 100, "Leon Russell"],
  ["Three Little Words", "F", 130, "Harry Ruby"],
  ["Till There Was You", "F", 100, "Meredith Willson"],
  ["Tonight", "F", 130, "Leonard Bernstein"],
  ["Too Close for Comfort", "F", 130, "Jerry Bock"],
  ["Watch What Happens", "Bb", 120, "Michel Legrand"],
  ["Way Down Yonder in New Orleans", "C", 130, "Turner Layton"],
  ["What a Wonderful World", "F", 66, "George David Weiss"],
  ["What Are You Doing the Rest of Your Life?", "Bb", 62, "Michel Legrand"],
  ["When You Wish upon a Star", "Bb", 66, "Leigh Harline"],
  ["Where Do You Start?", "Bb", 62, "Johnny Mandel"],
  ["Whispering", "C", 130, "John Schonberger"],
  ["You Are the Sunshine of My Life", "Ab", 100, "Stevie Wonder"],
  ["You Make Me Feel So Young", "Eb", 130, "Josef Myrow"],
  ["You Took Advantage of Me", "F", 130, "Richard Rodgers"],
  ["You're Nobody 'til Somebody Loves You", "C", 130, "Russ Morgan"],
  ["Waltz for Debby", "F", 170, "Bill Evans", "3/4"],
  ["Django", "Cm", 66, "John Lewis"],
  ["Milano", "Bb", 130, "John Lewis"],
  ["Skating in Central Park", "F", 100, "John Lewis"],
  ["Vendôme", "Cm", 130, "John Lewis"],
  ["Concorde", "C", 130, "John Lewis"],
  ["I Remember Clifford", "Bb", 62, "Benny Golson"],
  ["Killer Joe", "Gm", 130, "Benny Golson"],
  ["Park Avenue Petite", "F", 100, "Benny Golson"],
  ["Crystal Silence", "Em", 62, "Chick Corea"],
  ["La Fiesta", "Fm", 150, "Chick Corea"],
  ["Armando's Rhumba", "Am", 130, "Chick Corea"],
  ["Tones for Joan's Bones", "F", 130, "Chick Corea"],
  ["Matrix", "Dm", 210, "Chick Corea"],
  ["Sometime Ago", "Eb", 66, "Sergio Mihanovich"],
  ["Autumn Serenade", "Bb", 62, "Peter DeRose"],
  ["Basin Street Blues", "C", 90, "Spencer Williams"],
  ["St. James Infirmary", "Cm", 66, "Joe Primrose"],
  ["When the Saints Go Marching In", "C", 130, "Traditional"],
  ["Struttin' with Some Barbecue", "F", 130, "Lil Hardin Armstrong"],
  ["Muskrat Ramble", "Bb", 150, "Kid Ory"],
  ["Ain't Misbehavin'", "Eb", 120, "Fats Waller"],
  ["Handful of Keys", "Eb", 190, "Fats Waller"],
  ["Willow Tree", "Eb", 100, "Fats Waller"],
  ["Sweet Sue", "Eb", 130, "Victor Young"],
  ["Dinah", "C", 150, "Harry Akst"],
  ["Nagasaki", "Bb", 180, "Harry Warren"],
  ["Limehouse Blues", "G", 190, "Philip Braham"],
  ["Sweet Lorraine", "C", 130, "Cliff Burwell"],
  ["Indiana", "Bb", 190, "James Hanley"],
  ["Ja-Da", "C", 130, "Bob Carleton"],
  ["Jealousy", "Dm", 120, "Jacob Gade"],
  ["Ballin' the Jack", "C", 130, "Chris Smith"],
  ["Some of These Days", "C", 130, "Shelton Brooks"],
  ["Lady Be Good", "C", 180, "George Gershwin"],
  ["S'Posin'", "C", 130, "Paul Denniker"],
  ["Stardust", "C", 62, "Hoagy Carmichael"],
  ["Skylark", "Eb", 62, "Hoagy Carmichael"],
  ["Rockin' Chair", "Bb", 66, "Hoagy Carmichael"],
  ["Baltimore Oriole", "Ab", 100, "Hoagy Carmichael"],
  ["Ole Buttermilk Sky", "F", 100, "Hoagy Carmichael"],
  ["Two Sleepy People", "C", 110, "Hoagy Carmichael"],
  ["The Nearness of You", "F", 62, "Hoagy Carmichael"],
  ["I Get Along Without You Very Well", "Eb", 62, "Hoagy Carmichael"],
  ["Lazybones", "C", 100, "Hoagy Carmichael"],
  ["My Buddy", "C", 100, "Walter Donaldson"],
  ["Yes Sir, That's My Baby", "C", 150, "Walter Donaldson"],
  ["Makin' Whoopee", "Eb", 110, "Walter Donaldson"],
  ["My Blue Heaven", "C", 130, "Walter Donaldson"],
  ["Love Me or Leave Me", "Eb", 130, "Walter Donaldson"],
  ["At Sundown", "C", 130, "Walter Donaldson"],
  ["Carolina in the Morning", "C", 130, "Walter Donaldson"],
];

function normalizeKey(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9 ]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** Moves a trailing article ("Foggy Day, A") to the front so it reads and searches naturally. */
function tidyName(name: string): string {
  const match = /^(.*), (A|An|The)$/.exec(name);
  return match ? `${match[2]} ${match[1]}` : name;
}

/** A cheap dedupe key for `build()` — the full `nameId` runs `.normalize()`, which is a slow native
    call per string on Android (see `sortText.ts`), too costly to run ~630 times at module load. */
function quickId(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9 ]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/^(the|a|an) /, "");
}

function build(): Standard[] {
  const seen = new Set<string>();
  const list: Standard[] = [];
  for (const [rawName, key, bpm, composer, ts] of ROWS) {
    const name = tidyName(rawName);
    const id = quickId(name);
    if (seen.has(id)) continue;
    seen.add(id);
    list.push({ name, key, bpm, composer, timeSignature: ts ?? DEFAULT_TIME_SIGNATURE });
  }
  return sortByText(list, (s) => s.name);
}

export const STANDARDS: Standard[] = build();

// Built on first search rather than at module load — same slow-`.normalize()` reason as `quickId`.
let searchIndex: string[] | null = null;

/** Identifies a tune by name, ignoring case, punctuation and a leading "The". */
export function nameId(name: string): string {
  return normalizeKey(tidyName(name)).replace(/^(the|a|an) /, "");
}

/** Every word you type must appear somewhere in the title, composer or key. */
export function searchStandards(query: string): Standard[] {
  const words = normalizeKey(query).split(" ").filter(Boolean);
  if (words.length === 0) return STANDARDS;
  searchIndex ??= STANDARDS.map((s) => normalizeKey(`${s.name} ${s.composer} ${s.key}`));
  const index = searchIndex;
  return STANDARDS.filter((_, i) => words.every((w) => index[i].includes(w)));
}

export function standardToTune(standard: Standard): Tune {
  return {
    id: makeId(),
    name: standard.name,
    tempos: [{ id: makeId(), value: standard.bpm, enabled: true }],
    keys: [{ id: makeId(), value: standard.key, enabled: true }],
    timeSignature: standard.timeSignature,
    notes: "",
  };
}
