export const THEME_FIELDS = [
  { key: "background", label: "Page background" },
  { key: "surface", label: "Cards & sidebar" },
  { key: "surface-hover", label: "Hover / borders" },
  { key: "foreground", label: "Text" },
  { key: "muted", label: "Muted text" },
  { key: "accent", label: "Accent" },
  { key: "accent-hover", label: "Accent hover" },
  { key: "accent-foreground", label: "Text on accent" },
  { key: "overlay", label: "Modal backdrop" },
  { key: "danger", label: "Error" },
] as const;

export type ThemeColorKey = (typeof THEME_FIELDS)[number]["key"];
export type ThemeColors = Record<ThemeColorKey, string>;

export type ThemePreset = { id: string; label: string; colors: ThemeColors };

export const CUSTOM_THEME_ID = "custom";
export const OVERLAY_OPACITY = 0.6;

export const PRESETS: ThemePreset[] = [
  {
    id: "light",
    label: "Light",
    colors: {
      background: "#e8ecf1",
      surface: "#f4f6f9",
      "surface-hover": "#dde3ea",
      foreground: "#1e2833",
      muted: "#5c6878",
      accent: "#3870b2",
      "accent-hover": "#2d5e98",
      "accent-foreground": "#ffffff",
      overlay: "#1e2833",
      danger: "#c8475a",
    },
  },
  {
    id: "dark",
    label: "Dark",
    colors: {
      background: "#151c25",
      surface: "#1d2631",
      "surface-hover": "#28333f",
      foreground: "#d9e0e8",
      muted: "#8d9aaa",
      accent: "#72a3dc",
      "accent-hover": "#94bbe6",
      "accent-foreground": "#111821",
      overlay: "#000000",
      danger: "#e8848f",
    },
  },
  {
    id: "midnight",
    label: "Midnight",
    colors: {
      background: "#0b1020",
      surface: "#131a2e",
      "surface-hover": "#1c2540",
      foreground: "#e6ebff",
      muted: "#8b96b8",
      accent: "#4f8cff",
      "accent-hover": "#79a6ff",
      "accent-foreground": "#06101f",
      overlay: "#000010",
      danger: "#ff7a8a",
    },
  },
  {
    id: "forest",
    label: "Forest",
    colors: {
      background: "#0f1a14",
      surface: "#172620",
      "surface-hover": "#20342b",
      foreground: "#e4f2e8",
      muted: "#8fae9a",
      accent: "#4ade80",
      "accent-hover": "#86efac",
      "accent-foreground": "#06140b",
      overlay: "#000000",
      danger: "#f28797",
    },
  },
  {
    id: "sunset",
    label: "Sunset",
    colors: {
      background: "#1c1216",
      surface: "#2a1a20",
      "surface-hover": "#3a2229",
      foreground: "#fdeee6",
      muted: "#c49a8c",
      accent: "#fb923c",
      "accent-hover": "#fdba74",
      "accent-foreground": "#1c0d05",
      overlay: "#100000",
      danger: "#fb7185",
    },
  },
  {
    id: "nord",
    label: "Nord",
    colors: {
      background: "#2e3440",
      surface: "#3b4252",
      "surface-hover": "#434c5e",
      foreground: "#eceff4",
      muted: "#a3aec4",
      accent: "#88c0d0",
      "accent-hover": "#8fbcbb",
      "accent-foreground": "#2e3440",
      overlay: "#1a1e26",
      danger: "#bf616a",
    },
  },
  {
    id: "dracula",
    label: "Dracula",
    colors: {
      background: "#21222c",
      surface: "#282a36",
      "surface-hover": "#343746",
      foreground: "#f8f8f2",
      muted: "#a0a6c4",
      accent: "#bd93f9",
      "accent-hover": "#d0b0ff",
      "accent-foreground": "#21222c",
      overlay: "#000000",
      danger: "#ff5555",
    },
  },
  {
    id: "rose",
    label: "Rose",
    colors: {
      background: "#fdf2f4",
      surface: "#ffffff",
      "surface-hover": "#fbe3e8",
      foreground: "#3b1520",
      muted: "#94606d",
      accent: "#e11d48",
      "accent-hover": "#be123c",
      "accent-foreground": "#ffffff",
      overlay: "#3b1520",
      danger: "#b91c1c",
    },
  },
  {
    id: "solarized",
    label: "Solarized",
    colors: {
      background: "#fdf6e3",
      surface: "#eee8d5",
      "surface-hover": "#e4ddc6",
      foreground: "#073642",
      muted: "#657b83",
      accent: "#268bd2",
      "accent-hover": "#1e6fa8",
      "accent-foreground": "#fdf6e3",
      overlay: "#002b36",
      danger: "#dc322f",
    },
  },
  {
    id: "coffee",
    label: "Coffee",
    colors: {
      background: "#f3ebe2",
      surface: "#fbf6f0",
      "surface-hover": "#e8dccd",
      foreground: "#2b1d14",
      muted: "#7d6553",
      accent: "#8b5a2b",
      "accent-hover": "#6f4520",
      "accent-foreground": "#ffffff",
      overlay: "#2b1d14",
      danger: "#b3372f",
    },
  },
];

/**
 * A much longer tail of presets, modeled after well-known terminal/editor color schemes — shown
 * only behind the "See all" search (`components/ThemeSearchModal.tsx`), not in `ThemeModal`'s own
 * main grid, so that grid stays the same small, quick-pick set it's always been (`PRESETS` above,
 * untouched by this addition). Hex values are from memory of each scheme's own well-known
 * palette, not pulled from each project's live source in this sandbox (no network access here) —
 * close to the real thing, not guaranteed pixel-identical to the original.
 */
export const MORE_PRESETS: ThemePreset[] = [
  {
    id: "gruvbox-dark",
    label: "Gruvbox Dark",
    colors: {
      background: "#282828",
      surface: "#3c3836",
      "surface-hover": "#504945",
      foreground: "#ebdbb2",
      muted: "#a89984",
      accent: "#fe8019",
      "accent-hover": "#fabd2f",
      "accent-foreground": "#282828",
      overlay: "#1d2021",
      danger: "#fb4934",
    },
  },
  {
    id: "gruvbox-light",
    label: "Gruvbox Light",
    colors: {
      background: "#fbf1c7",
      surface: "#f2e5bc",
      "surface-hover": "#ebdbb2",
      foreground: "#3c3836",
      muted: "#7c6f64",
      accent: "#d65d0e",
      "accent-hover": "#af3a03",
      "accent-foreground": "#fbf1c7",
      overlay: "#3c3836",
      danger: "#9d0006",
    },
  },
  {
    id: "monokai",
    label: "Monokai",
    colors: {
      background: "#272822",
      surface: "#3e3d32",
      "surface-hover": "#49483e",
      foreground: "#f8f8f2",
      muted: "#90908a",
      accent: "#a6e22e",
      "accent-hover": "#c2e77a",
      "accent-foreground": "#272822",
      overlay: "#1b1c17",
      danger: "#f92672",
    },
  },
  {
    id: "one-dark",
    label: "One Dark",
    colors: {
      background: "#282c34",
      surface: "#2c313a",
      "surface-hover": "#3a3f4b",
      foreground: "#abb2bf",
      muted: "#5c6370",
      accent: "#61afef",
      "accent-hover": "#82c6f7",
      "accent-foreground": "#282c34",
      overlay: "#21252b",
      danger: "#e06c75",
    },
  },
  {
    id: "one-light",
    label: "One Light",
    colors: {
      background: "#fafafa",
      surface: "#ffffff",
      "surface-hover": "#eaeaeb",
      foreground: "#383a42",
      muted: "#a0a1a7",
      accent: "#4078f2",
      "accent-hover": "#2a5bd7",
      "accent-foreground": "#ffffff",
      overlay: "#383a42",
      danger: "#e45649",
    },
  },
  {
    id: "tokyo-night",
    label: "Tokyo Night",
    colors: {
      background: "#1a1b26",
      surface: "#24283b",
      "surface-hover": "#2f334d",
      foreground: "#c0caf5",
      muted: "#565f89",
      accent: "#7aa2f7",
      "accent-hover": "#89b4fa",
      "accent-foreground": "#1a1b26",
      overlay: "#13141c",
      danger: "#f7768e",
    },
  },
  {
    id: "catppuccin-mocha",
    label: "Catppuccin Mocha",
    colors: {
      background: "#1e1e2e",
      surface: "#313244",
      "surface-hover": "#45475a",
      foreground: "#cdd6f4",
      muted: "#a6adc8",
      accent: "#89b4fa",
      "accent-hover": "#b4befe",
      "accent-foreground": "#1e1e2e",
      overlay: "#11111b",
      danger: "#f38ba8",
    },
  },
  {
    id: "catppuccin-latte",
    label: "Catppuccin Latte",
    colors: {
      background: "#eff1f5",
      surface: "#e6e9ef",
      "surface-hover": "#dce0e8",
      foreground: "#4c4f69",
      muted: "#6c6f85",
      accent: "#1e66f5",
      "accent-hover": "#7287fd",
      "accent-foreground": "#eff1f5",
      overlay: "#4c4f69",
      danger: "#d20f39",
    },
  },
  {
    id: "ayu-dark",
    label: "Ayu Dark",
    colors: {
      background: "#0a0e14",
      surface: "#131721",
      "surface-hover": "#1b212c",
      foreground: "#b3b1ad",
      muted: "#626a73",
      accent: "#ffb454",
      "accent-hover": "#ffd180",
      "accent-foreground": "#0a0e14",
      overlay: "#000000",
      danger: "#ff3333",
    },
  },
  {
    id: "night-owl",
    label: "Night Owl",
    colors: {
      background: "#011627",
      surface: "#0b2942",
      "surface-hover": "#13395a",
      foreground: "#d6deeb",
      muted: "#637777",
      accent: "#82aaff",
      "accent-hover": "#a6c6ff",
      "accent-foreground": "#011627",
      overlay: "#000000",
      danger: "#ef5350",
    },
  },
  {
    id: "material-dark",
    label: "Material",
    colors: {
      background: "#263238",
      surface: "#2e3c43",
      "surface-hover": "#37474f",
      foreground: "#eeffff",
      muted: "#546e7a",
      accent: "#82aaff",
      "accent-hover": "#89ddff",
      "accent-foreground": "#263238",
      overlay: "#102027",
      danger: "#f07178",
    },
  },
  {
    id: "oceanic-next",
    label: "Oceanic Next",
    colors: {
      background: "#1b2b34",
      surface: "#243b4a",
      "surface-hover": "#2d4a5c",
      foreground: "#cdd3de",
      muted: "#65737e",
      accent: "#6699cc",
      "accent-hover": "#8fb8e0",
      "accent-foreground": "#1b2b34",
      overlay: "#0f1a21",
      danger: "#ec5f67",
    },
  },
  {
    id: "rose-pine",
    label: "Rosé Pine",
    colors: {
      background: "#191724",
      surface: "#1f1d2e",
      "surface-hover": "#26233a",
      foreground: "#e0def4",
      muted: "#6e6a86",
      accent: "#c4a7e7",
      "accent-hover": "#ebbcba",
      "accent-foreground": "#191724",
      overlay: "#0f0e17",
      danger: "#eb6f92",
    },
  },
  {
    id: "rose-pine-dawn",
    label: "Rosé Pine Dawn",
    colors: {
      background: "#faf4ed",
      surface: "#fffaf3",
      "surface-hover": "#f2e9e1",
      foreground: "#575279",
      muted: "#9893a5",
      accent: "#907aa9",
      "accent-hover": "#d7827e",
      "accent-foreground": "#faf4ed",
      overlay: "#575279",
      danger: "#b4637a",
    },
  },
  {
    id: "everforest-dark",
    label: "Everforest",
    colors: {
      background: "#2d353b",
      surface: "#343f44",
      "surface-hover": "#3d484d",
      foreground: "#d3c6aa",
      muted: "#859289",
      accent: "#a7c080",
      "accent-hover": "#83c092",
      "accent-foreground": "#2d353b",
      overlay: "#1e2326",
      danger: "#e67e80",
    },
  },
  {
    id: "synthwave-84",
    label: "Synthwave '84",
    colors: {
      background: "#262335",
      surface: "#2a2139",
      "surface-hover": "#34294f",
      foreground: "#f4eee4",
      muted: "#848bbd",
      accent: "#ff7edb",
      "accent-hover": "#ffb3f0",
      "accent-foreground": "#262335",
      overlay: "#100b1c",
      danger: "#fe4450",
    },
  },
  {
    id: "horizon",
    label: "Horizon",
    colors: {
      background: "#1c1e26",
      surface: "#232530",
      "surface-hover": "#2e303e",
      foreground: "#e0e0e0",
      muted: "#6c6f93",
      accent: "#26bbd9",
      "accent-hover": "#59e1e3",
      "accent-foreground": "#1c1e26",
      overlay: "#16161c",
      danger: "#e95678",
    },
  },
  {
    id: "kanagawa",
    label: "Kanagawa",
    colors: {
      background: "#1f1f28",
      surface: "#2a2a37",
      "surface-hover": "#363646",
      foreground: "#dcd7ba",
      muted: "#727169",
      accent: "#7e9cd8",
      "accent-hover": "#a6c3f4",
      "accent-foreground": "#1f1f28",
      overlay: "#16161d",
      danger: "#e82424",
    },
  },
  {
    id: "zenburn",
    label: "Zenburn",
    colors: {
      background: "#3f3f3f",
      surface: "#4f4f4f",
      "surface-hover": "#5f5f5f",
      foreground: "#dcdccc",
      muted: "#9fafaf",
      accent: "#8cd0d3",
      "accent-hover": "#93e0e3",
      "accent-foreground": "#3f3f3f",
      overlay: "#2b2b2b",
      danger: "#cc9393",
    },
  },
  {
    id: "nightfox",
    label: "Nightfox",
    colors: {
      background: "#192330",
      surface: "#212e3f",
      "surface-hover": "#29394f",
      foreground: "#cdcecf",
      muted: "#71839b",
      accent: "#719cd6",
      "accent-hover": "#86e1fc",
      "accent-foreground": "#192330",
      overlay: "#131a24",
      danger: "#c94f6d",
    },
  },
];

export const ALL_PRESETS: ThemePreset[] = [...PRESETS, ...MORE_PRESETS];

export function getPreset(id: string): ThemePreset | undefined {
  return ALL_PRESETS.find((p) => p.id === id);
}

export function isValidHex(value: string): boolean {
  return /^#[0-9a-fA-F]{6}$/.test(value);
}

export function isDarkColors(colors: ThemeColors): boolean {
  const hex = isValidHex(colors.background) ? colors.background : "#ffffff";
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b < 0.5;
}
