#!/usr/bin/env python3
"""Generates src/lib/notation/glyphData.ts from the exact fonts VexFlow embeds on the web.

VexFlow 5 ships Bravura (SMuFL music font) and Academico (text) as base64 woff2 inside
`vexflow/build/esm/src/fonts/*.js`; the web app loads those and measures/draws every notation glyph
with them. This pulls the same binaries back out and writes each needed glyph's advance width,
bounding box and outline (as an SVG path, y-down, in font units) so the app can measure and draw
the notation identically without loading fonts on the device. See `vexflowNative.ts`.

Run from apps/mobile (needs fonttools + brotli), e.g.:
  nix shell --impure --expr 'with import <nixpkgs> {}; python3.withPackages (p: [p.fonttools p.brotli])' \
    -c python3 scripts/extract-notation-glyphs.py
"""
import base64
import io
import json
import os
import re

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

HERE = os.path.dirname(os.path.abspath(__file__))
FONTS_DIR = os.path.join(HERE, '..', 'node_modules', 'vexflow', 'build', 'esm', 'src', 'fonts')
OUT = os.path.join(HERE, '..', 'src', 'lib', 'notation', 'glyphData.ts')

# Which characters to keep from each font. Academico: printable ASCII (captions/labels). Bravura:
# the SMuFL ranges the Random Sticking Warmup notation draws from — noteheads, flags, clefs,
# repeat dots, tuplet/time-signature digits, rests — plus generous neighbours so a small change to
# what's drawn doesn't silently lose a glyph (missing glyphs log a dev warning).
RANGES = {
    'Academico': ('academico.js', [(0x20, 0x7E)]),
    'Bravura': ('bravura.js', [
        (0xE030, 0xE04F),  # barlines, repeat dots
        (0xE050, 0xE07F),  # clefs (incl. unpitched percussion E069/E06A)
        (0xE080, 0xE09F),  # time signature digits
        (0xE0A0, 0xE0FF),  # noteheads
        (0xE1E7, 0xE1E7),  # augmentation dot
        (0xE240, 0xE25F),  # flags
        (0xE4E0, 0xE4FF),  # rests
        (0xE880, 0xE88F),  # tuplet digits
    ]),
}


def load(js_name):
    src = open(os.path.join(FONTS_DIR, js_name), encoding='utf8').read()
    b64 = re.search(r"base64,([^'\"]+)", src).group(1)
    return TTFont(io.BytesIO(base64.b64decode(b64)))


def fmt(v):
    s = ('%.1f' % v).rstrip('0').rstrip('.')
    return '0' if s in ('-0', '') else s


fonts = {}
for name, (js_name, ranges) in RANGES.items():
    font = load(js_name)
    cmap = font.getBestCmap()
    glyph_set = font.getGlyphSet()
    hmtx = font['hmtx']
    glyphs = {}
    for lo, hi in ranges:
        for cp in range(lo, hi + 1):
            gname = cmap.get(cp)
            if gname is None:
                continue
            pen = SVGPathPen(glyph_set, ntos=fmt)
            glyph_set[gname].draw(TransformPen(pen, (1, 0, 0, -1, 0, 0)))
            from fontTools.pens.boundsPen import BoundsPen
            bp = BoundsPen(glyph_set)
            glyph_set[gname].draw(bp)
            b = bp.bounds or (0, 0, 0, 0)
            glyphs[chr(cp)] = {
                'a': hmtx[gname][0],
                'b': [round(x, 1) for x in b],
                'd': pen.getCommands(),
            }
    hhea = font['hhea']
    fonts[name] = {
        'unitsPerEm': font['head'].unitsPerEm,
        'ascender': hhea.ascent,
        'descender': hhea.descent,
        'glyphs': glyphs,
    }
    print(name, len(glyphs), 'glyphs')

with open(OUT, 'w', encoding='utf8') as f:
    f.write('// Generated by scripts/extract-notation-glyphs.py — do not edit by hand.\n')
    f.write('// Glyph metrics/outlines from the Bravura and Academico fonts VexFlow embeds\n')
    f.write('// (Bravura: SIL OFL 1.1, Steinberg Media Technologies; Academico: SIL OFL 1.1).\n\n')
    f.write('export type GlyphFont = {\n  unitsPerEm: number;\n  ascender: number;\n  descender: number;\n')
    f.write('  /** a = advance width, b = [xMin, yMin, xMax, yMax] (y up), d = outline path (y down). */\n')
    f.write('  glyphs: Record<string, { a: number; b: [number, number, number, number]; d: string }>;\n};\n\n')
    f.write('export const NOTATION_FONTS: Record<string, GlyphFont> = ')
    f.write(json.dumps(fonts, ensure_ascii=True, separators=(',', ':')))
    f.write(';\n')
print('wrote', OUT, os.path.getsize(OUT), 'bytes')
